### ISSUE TITLE
[BUG] missing fields stderr, stdin and stdout in initializer of Config

### ISSUE THREAD

**Issue by Albertchamberlain** [eunomia-bpf/wasm-bpf#101]
**Describe the bug**
missing fields `stderr`, `stdin` and `stdout` in initializer of `Config`
**To Reproduce**

just  run  cargo install wasm-bpf 

**Expected behavior**
Compiling success

**Screenshots**
![image](https://user-images.githubusercontent.com/47343901/232791365-b6781168-239d-4770-b444-bf024e540ebe.png)

**Desktop (please complete the following information):**

* OS: [Ubuntu]
* Version [22.04.1 LTS]

**Additional context**
use cargo mirror ：mirrors.tuna.tsinghua.edu.cn

**Comment by DeanYang121** [comment]
i meet same error

OS：centos7
kernel： Linux build-redis 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Albertchamberlain** [comment]
> @DeanYang121 @Albertchamberlain The version of `wasm-bpf` you used has been outdated. I've uploaded a newer version (v0.2.0), have a try for that

Thank You !!!
