### ISSUE TITLE
[BUG] examples sockops can’t  "make" success

### ISSUE THREAD

**Issue by Albertchamberlain** [eunomia-bpf/wasm-bpf#108]
**Describe the bug**

amos@samsung:~/wasm-bpf/examples/sockops$ make
cd ../../runtime/cpp/third_party/bpftool/src && make
/bin/sh: 1: cd: can't cd to ../../runtime/cpp/third_party/bpftool/src
make: *** [Makefile:48：../../runtime/cpp/third_party/bpftool/src/bpftool] 错误 2

**To Reproduce**

run make in this path " ~/wasm-bpf/examples/sockops"

**Expected behavior**
make success

**Screenshots**
![image](https://user-images.githubusercontent.com/47343901/236188860-57778889-6136-487d-aac5-dad21dcfbfc3.png)

**Desktop (please complete the following information):**

OS: [Ubuntu]
Version [22.04.1 LTS]

**Comment by Officeyutong** [comment]
Did you remember to update the submodules? Try clone this repo with `git clone --recursive https://github.com/eunomia-bpf/wasm-bpf`

**Comment by Albertchamberlain** [comment]
Thanks

**Comment by Albertchamberlain** [comment]
git clone --recursive git@github.com:eunomia-bpf/wasm-bpf.git
