### ISSUE TITLE
[BUG]  can't pull wasm-bpf

### ISSUE THREAD

**Issue by Albertchamberlain** [eunomia-bpf/wasm-bpf#109]
**Describe the bug**
![image](https://user-images.githubusercontent.com/47343901/236189904-5b40e25b-7446-41cb-967a-8f270fce1549.png)

OS: [Ubuntu]
Version [22.04.1 LTS]

**Comment by Officeyutong** [comment]
`wasm-bpf` is a rust program. It should be installed using `cargo install wasm-bpf`
