### ISSUE TITLE
[BUG]  xdp capture nothing

### ISSUE THREAD

**Issue by Albertchamberlain** [eunomia-bpf/wasm-bpf#114]
**Describe the bug**
cat /sys/kernel/debug/tracing/trace_pipe  shows nothing

**To Reproduce**
As the readme file say，
First，execute make，but error happen，rust need newer version，I update rust 1.69 in root mode.
then，execute  "cargo install wasm-bpf"
last，make agin，I get the xdp.wasm，and run "wasm-bpf xdp.wasm wlp2s0".   show  "Load and attach BPF xdp successfully"
but, when i execute "cat /sys/kernel/debug/tracing/trace_pipe", there is nothing i can get.

**Expected behavior**

**Screenshots**
![image](https://github.com/eunomia-bpf/wasm-bpf/assets/47343901/4f4e1de6-30fb-4616-865f-a735b15a3bc0)
![image](https://github.com/eunomia-bpf/wasm-bpf/assets/47343901/45f7fb94-f685-4a1b-9844-be03bcae36c9)

It looks like xdp is not mounted on wlp2s0 🤣
**Desktop (please complete the following information):**
* OS: [Ubuntu]
* Version [22.04.1 LTS]

**Comment by Officeyutong** [comment]
I'm sorry that wasm-bpf does not support XDP now..

**Comment by Officeyutong** [comment]
I'm sorry that wasm-bpf-rs currently does not support XDP. But the C++version supports, you could run `IMPL=cpp make` in the examples directory to obtain the executable of the C++ version. We are working to add xdp support for the rust version (see #121 )

**Comment by Albertchamberlain** [comment]
Thank You Very Much 👍  ：）

**Comment by Officeyutong** [comment]
@Albertchamberlain The rust implementation of wasm-bpf was added with XDP support now, have a try for that

**Comment by Officeyutong** [comment]
> > @Albertchamberlain The rust implementation of wasm-bpf was added with XDP support now, have a try for that wasm-bpf的rust实现现在添加了XDP支持，可以尝试一下
> 
> Cool，Thank You :)

Just close this issue if it worked :)
