### ISSUE TITLE
docker run failed when compile ebpf

### ISSUE THREAD

**Issue by jinglina** [eunomia-bpf/wasm-bpf#117]
**Describe the bug**
when I run `docker run` as what wasm-bpf readme(https://github.com/eunomia-bpf/wasm-bpf/tree/main) in `Running a standalone Wasm-eBPF program` part. It fails because `no matching manifest for linux/amd64 in the manifest list entries` when `pulling form  eunomia-bpf/wasm-bpf` . 
I noticed an [issue](https://github.com/eunomia-bpf/wasm-bpf/issues/109) related .But how to figure it out to compile smoothly using this tool?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. Windows]
* Version [e.g. 10]

**Additional context**

**Comment by Albertchamberlain** [comment]
https://github.com/eunomia-bpf/wasm-bpf/issues/109
1.  cargo install wasm-bpf  
2. wasm-bpf  runqlat.wasm
3. you will see this  👇
![image](https://github.com/eunomia-bpf/wasm-bpf/assets/47343901/6d1a0ff6-02f0-4bc4-b111-eb2423099068)
