### ISSUE TITLE
[FEATURE] Compare the performance between wasm-bpf and native libbpf on CPU, memory and disk usage

### ISSUE THREAD

**Issue by Officeyutong** [eunomia-bpf/wasm-bpf#127]

**Comment by Officeyutong** [comment]
Initial plan:
- Measure the CPU, IO, and memory usage of the userspace program of eBPF programs using wasm-bpf and native bpf
- Kernel space programs are unnecessary to measure. Kernel programs loaded by wasm-bpf and native libbpf should behave the same

**Comment by Albertchamberlain** [comment]
cool feature！

**Comment by blue-troy** [comment]
Assuming my program is written in rust/go, will wasm improve the performance of my user mode program?

**Comment by yunwei37** [comment]
Completed.

> Assuming my program is written in rust/go, will wasm improve the performance of my user mode program?

I think compare to native rust/go program, wasm cannot improve the performance. Wasm is typically slower than native.
