### ISSUE TITLE
[FEATURE] add unit test for runtime

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/wasm-bpf#13]
**Is your feature request related to a problem? Please describe.**

We need to enable codecov and improve unit tests for the runtime，as we did in eunomia-bpf project.

**Comment by try-agaaain** [comment]
Does it means we need write a unit test for rust version? or just write a ci test workflow for cpp version?

**Comment by yunwei37** [comment]
maybe a set of tests compiled to wasm, and test both rust and cpp
 Version?

**Comment by try-agaaain** [comment]
Ok, I'll finish it later.

**Comment by yunwei37** [comment]
You may also need to add tests for rust runtime in runtime/wasm-bpf-rs.
