### ISSUE TITLE
Prototyping a rust wasm-bpf runtime based on wasmtime

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/wasm-bpf#15]
We need to prototype a runtime based on wasmtime because:

- rust may be safer than C/cpp, and cargo may be a better package manage approach and build systems than git submodule/cmake
- We are not very familiar with cmake...
- wasmtime has a better support on component modal and better ecosystem

The current version wamr runtime may still remain, for a more lightweight usecases and better support with libbpf (C/C++ library).

The rust library to load and operate eBPF programs can be aya-rs.

Any suggestions?

**Comment by Officeyutong** [comment]
Already solved https://github.com/eunomia-bpf/wasm-bpf/tree/main/runtime/rust
