### ISSUE TITLE
[FEATURE] Support mapping directories & files into the wasm guest

### ISSUE THREAD

**Issue by Officeyutong** [eunomia-bpf/wasm-bpf#38]
See https://docs.rs/wasmtime-wasi/latest/wasmtime_wasi/struct.WasiCtx.html for API details

**Comment by yunwei37** [comment]
This can be done by intergrading with other runtimes. For example, Wasmedge: https://github.com/WasmEdge/WasmEdge/pull/2314

There's no need to maintain our own executable in this repo.
