### ISSUE TITLE
Split wasm_main for better use as a library.

### ISSUE THREAD

**Issue by ocfox** [eunomia-bpf/wasm-bpf#6]
Function [wasm_main()](https://github.com/eunomia-bpf/wasm-bpf/blob/main/src/wasm-bpf.cpp#LL272C5-L272C72) has argc and argv as arguments.
It may not be convenient to use, is it better to separate the parameter resolution into another function?
Such as `wasm_main(current_config.program_data_buffer, 0, NULL);`, this seems like an odd approach.

**Comment by yunwei37** [comment]
Thanks! May be You could provide more examples about the API design?

Note that the wasm-bpf runtime library mainly works as an example of how to build the runtime, so please don't make it too complex.

**Comment by yunwei37** [comment]
Thanks! May be You could provide more examples about the API design?

Note that the wasm-bpf runtime library mainly works as an example of how to build the runtime, so please don't make it too complex.

**Comment by ocfox** [comment]
Ok, I will try to modify and make a pull request.

**Comment by yunwei37** [comment]
It's done by using the rust library.
