### ISSUE TITLE
[FEATURE] Add API to collect output from stdio

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/wasm-bpf#74]
see what we have done in wasm-bpf-rs

Use a pipe to send and receive data from stdio.

Reference: https://petermalmgren.com/serverside-wasm-data/

**Comment by yunwei37** [comment]
See https://github.com/eunomia-bpf/wasm-bpf/blob/main/runtime/wasm-bpf-rs/src/lib.rs#L200-L200, please complete the test cases.

**Comment by Officeyutong** [comment]
Similar to https://github.com/eunomia-bpf/wasm-bpf/pull/79, we can directly use `ReadableWritePipe` to receive data from a wasm program during its running

**Comment by yunwei37** [comment]
this issue is finished by #79.
