### ISSUE TITLE
[FEATURE] add api to stop an wasm-bpf program

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/wasm-bpf#75]
see wasm-bpf-rs，an api need to be add to stop or kill a running wasm program.

**Comment by kushalnl7** [comment]
Hi @yunwei37, I am interested in this. Can you please explain briefly what needs to be added and which files are required to be changed?

**Comment by yunwei37** [comment]
Thank you very much!

Sorry for my missing more descriptions...

you can look into the https://github.com/eunomia-bpf/wasm-bpf/blob/main/runtime/wasm-bpf-rs/src/lib.rs#L81-L81
, currently we have functions to start running the wasm-ebpf program, but there is no API to stop and kill the running wasm module while not existing the process.

Can you help us find a way to kill a wasm-bpf program? You may need to modify the lib.rs file and add a test.

Maybe you can look into the wasmtime mannual to find how to stop and kill the wasm module.

**Comment by yunwei37** [comment]
a possible solution can be using a trap，see https://github.com/Officeyutong/wasm-bpf/blob/4d25f703865203631271afe39c5245475fee9ca6/runtime/wasm-bpf-rs/src/lib.rs#L223 and #79 

It would be suitable for this issue, but not for #74 ...

**Comment by Officeyutong** [comment]
Should this issue be closed now? Or we still need ways to pause and resume a wasm program?
