### ISSUE TITLE
[FEATURE] Remove all unsafe ffi bindings to libbpf-sys in wasm-bpf-rs

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/wasm-bpf#92]
**Is your feature request related to a problem? Please describe.**

Currently we have a lot of unsafe blocks in wasm-bpf-rs due to the ffi binding to libbpf. They should be removed or contribute to libbpf-rs.

**Describe the solution you'd like**

- remove all unsafe blocks
- contribute to libbpf-rs.

**Comment by Officeyutong** [comment]
`libbpf-rs` was updated now, we can adapt the new features and remove most of the unsafe FFI calls.
